### ISSUE TITLE
Laggy and stuttering data?

### ISSUE THREAD

**Issue by ludzeller** [anastasiadevana/HeadphoneMotion#1]
The incoming data appears to be lagging by about 100-200ms. Is that normal and the best performance that we can get from that API?

Also, the data seems to be sampled at around 30hz... Can you confirm that or is it possible to get 60hz?

Fixing the lag would be more important for my application though... (spatializing mono sources and looking around in ambisonics spheres)

Thanks!

**Comment by anastasiadevana** [comment]
Gah, what is this "Issues" tab (sorry!)
What you're seeing is accurate and consistent with how Headphone tracking API currently works. There's no way to set the motion update rate, and it seems to float somewhere around 25 Hz from my observations. Unfortunately, the latency is also just how it works for now. Someone actually measured it properly: https://kinicho.medium.com/latency-in-spatial-audio-57236c15f243
