### ISSUE TITLE
Can this be debugged directly on unity without using build to the iphone?

### ISSUE THREAD

**Issue by Adilic** [anastasiadevana/HeadphoneMotion#3]
I can't run this sample program on my computer,And when trying to run the base code, the console prompts that the API can only run on IOS devices. This means that when I want to write something with it, I need to build it into my phone every time I debug it, so I want to ask if I can run it directly on unity

**Comment by anastasiadevana** [comment]
@Adilic to my knowledge the headphone motion API currently only works on an iOS device. So unfortunately yes, you have to make a build every time. What I've done in the past when I needed to get some kind of motion in the Unity editor, was get actual iPhone motion data via OSC into Unity. I even clipped the phone to my headphones at some point :) But that's a pretty major workaround, so may or may not be worth it, depending on what you're trying to achieve.

**Comment by Adilic** [comment]
HI：

Thank you very much for your reply. I want to use AirPods to do some action
control in unity, but I have given up because I can't debug it directly.

Thank you for telling me this.

Anastasia Devana ***@***.***> 于2021年9月30日周四 上午1:58写道：

**Comment by anastasiadevana** [comment]
Closing as resolved.
