### ISSUE TITLE
Tracking in the background?

### ISSUE THREAD

**Issue by erik-valtechsd** [anastasiadevana/HeadphoneMotion#5]
Thanks for this great plugin. One question, is there a way to get it to work in the background? I can't find anywhere in the API documentation that its not allowed, so I'm assuming this functionality is possible?

**Comment by anastasiadevana** [comment]
Hi there! Glad you're enjoying it!
I haven't tried it myself, but don't see why not. You would have to set up your Unity app to run in the background.
This thread is quite old, but might be a place to start: https://forum.unity.com/threads/how-do-i-get-the-audio-running-in-background-ios.319602/
