### ISSUE TITLE
Headphones not connected 

### ISSUE THREAD

**Issue by ah3243** [anastasiadevana/HeadphoneMotion#6]
hi great plugin! 
I'm not able to get it to recognise the airpods pro I'm using though. They work normally and `Headphone motion is available` but it says `Headphones are not connected`. 
I'm getting this hang risk if that could be a cause?

`Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a thread without a QoS class specified. Investigate ways to avoid priority inversions`

**Comment by anastasiadevana** [comment]
Hi there!
I haven't seen this message, but I also haven't tested the plugin with the latest Xcode. Is this an error or more of a warning/info message?
If info/warning, I think it might be a red herring.
Please check the following:
1) your headphones support head tracking (they need to be AirPods Pro or AirPods Max)
2) you gave permission to access motion data at the start of your app (if not, I think you can still give permission in the system settings somewhere)

I used the plugin in this publically available app: https://apps.apple.com/us/app/uo-knight-campus/id1531935077
Does the head tracking work for you in the app (you should hear spatial audio respond correctly when you turn your head)?

**Comment by ah3243** [comment]
Ok it think i found the problem, the airpods pros i was using aren't genuine or the motion tracking doesn't work on them. Which is disappointing. I'll have to try it again with some new airpods.

**Comment by anastasiadevana** [comment]
Bummer :(
